import { writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { loadAllGames, defaultGamesDir } from '../src/loader/index.js';

const outFile = resolve(import.meta.dirname, '../src/definitions/games.ts');

const gamesDir = process.env['SCOREKEEP_GAMES_DIR'] || defaultGamesDir();
const { games, errors } = loadAllGames(gamesDir);

if (errors.length > 0) {
  console.error('Failed to load game definitions:');
  for (const err of errors) {
    console.error(`  ${err.filePath}: ${err.message}`);
    if (err.details) {
      for (const detail of err.details) {
        console.error(`    - ${detail}`);
      }
    }
  }
  process.exit(1);
}

const ids = Object.keys(games).sort();
const sorted = Object.values(games).sort((a, b) =>
  a.game.name.localeCompare(b.game.name),
);

const source = `// Auto-generated by scripts/generate-definitions.ts — do not edit
import type { GameDefinition } from '../types/game.js';

export const games: Record<string, GameDefinition> = ${JSON.stringify(games, null, 2)} as unknown as Record<string, GameDefinition>;

export const gameList: GameDefinition[] = ${JSON.stringify(sorted, null, 2)} as unknown as GameDefinition[];

export const gameIds: string[] = ${JSON.stringify(ids)};
`;

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, source, 'utf-8');

console.log(`Generated ${ids.length} game definitions → ${outFile}`);
